# Generated by Django 5.2.7 on 2025-10-18 16:05

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lycee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ninja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('classe', models.CharField(max_length=50)),
                ('lycee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presence.lycee')),
            ],
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=False)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fait_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lycee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presence.lycee')),
                ('ninja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presence.ninja')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presence.session')),
            ],
            options={
                'unique_together': {('ninja', 'session', 'date')},
            },
        ),
    ]
