# Generated by Django 5.2.7 on 2025-10-19 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0002_equipe_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
